# -----------------------------------------------------------------------------
#
# Match abstracts to microsporidia host data
#
# Jason Jiang - Created: 2022/05/09
#               Last edited: 2022/05/09
#
# Mideo Lab - Microsporidia text mining
#
# Add host data from Supplemental Table S1 from Murareanu et al. to manually
# extracted microsporidia abstract data (manually_collect_abstracts.xlsx,
# generated by src/organize_species_papers.R)
#
#
# -----------------------------------------------------------------------------

library(tidyverse)
library(readxl)

################################################################################

abstracts <- read_xlsx('../../data/manually_collect_abstracts.xlsx') %>%
  # fix weird issue with true/false being turned into dates by xlsx format
  mutate(foreign = ifelse(!is.na(foreign), TRUE, FALSE))

microsp_data <- read_csv('../../data/microsporidia_species.csv') %>%
  rename(species = `Species Name`, hosts = `Natural Host(s)`)

# add microsporidia species trait data to abstracts dataframe
abstracts <- merge(x = abstracts, y = microsp_data,
                   by = 'species', all = TRUE) %>%
  filter(!is.na(first_paper_reference))

# write the abstracts dataframe, now with traits information, to the data folder
write_csv(abstracts, '../../data/abstracts_traits.csv')