# -----------------------------------------------------------------------------
#
# Match abstracts to microsporidia host data
#
# Jason Jiang - Created: 2022/05/09
#               Last edited: 2022/05/09
#
# Mideo Lab - Microsporidia text mining
#
# Add host data from Supplemental Table S1 from Murareanu et al. to manually
# extracted microsporidia abstract data (manually_collect_abstracts.xlsx,
# generated by src/organize_species_papers.R)
#
#
# -----------------------------------------------------------------------------

library(tidyverse)
library(readxl)

################################################################################

abstracts <- read_xlsx('../../data/manually_collect_abstracts.xlsx') %>%
  # fix weird issue with true/false being turned into dates by xlsx format
  mutate(foreign = ifelse(!is.na(foreign), TRUE, FALSE))

microsp_data <- read_csv('../../data/microsporidia_species.csv')

# Create new dataframe just for microsporidia host data
host_data <- microsp_data %>%
  rename(species = `Species Name`, hosts = `Natural Host(s)`) %>%
  select(species, hosts)

# add host data to abstracts dataframe
abstracts <- merge(x = abstracts, y = host_data, by = 'species', all.x = TRUE)

# write the abstracts dataframe, now with host information, to the data folder
write_csv(abstracts, '../../data/abstracts_hosts_matched.csv')