# -----------------------------------------------------------------------------
#
# Evaluate accuracy of predicted microsporidia traits
#
# Jason Jiang - Created: 2022/05/17
#               Last edited: 2022/05/17
#
# Mideo Lab - Microsporidia text mining
#
#
# -----------------------------------------------------------------------------

library(tidyverse)

################################################################################

# Dataframe of predicted microsporidia traits from microsporidia paper titles
# and abstracts, generated by spacy_extract_traits.py
microsp_data <- read_csv('../../results/microsp_predictions.csv')

################################################################################

## Evaluate predicted microsporidia species names

evaluate_predicted_microsp <- function(predicted_microsp,
                                       species) {
  # ---------------------------------------------------------------------------
  # Evaluate if a microsporidia species name was correctly predicted by
  # spacy_extract_traits.py, based on if predicted name matches manually
  # recorded name.
  # ---------------------------------------------------------------------------
  if (is.na(predicted_microsp)) {
    return(FALSE)
  }
  # Remove alternate species names + numbering
  species <-
    str_remove_all(str_remove_all(species, ' ?\\(.+'), ' ?[1-9][0-9]*')
  
  # correct prediction if actual species name is a substring of the predicted
  # species name
  return(str_detect(predicted_microsp, species))
}

evaluate_predicted_microsp <- Vectorize(evaluate_predicted_microsp,
                                        vectorize.args = c('predicted_microsp',
                                                           'species'))

species_check <- microsp_data %>%
  select(species, predicted_microsp, first_paper_title, abstract) %>%
  mutate(correct_prediction = evaluate_predicted_microsp(predicted_microsp,
                                                         species))

# 44% accuracy
# Cases of failure: multi-species papers, unrecognized new species patterns,
# species name only given in full paper, abbreviated species name given
# (ex: A. caspius), and genus is mentioned somewhere else in the paper
species_accuracy <- sum(species_check$correct_prediction) / nrow(species_check)

################################################################################

## Evaluate predicted localities
get_predicted_locality_precision_recall <- function(pred_loc, loc) {
  # Locality column is inconsistently formatted right now, so this doesn't work
  pred_loc <- str_split(pred_loc, '; ')[[1]]  # separate into vector of locations
  loc <- str_split(loc, '\\)?; ')[[1]]
  
  # Remove parenthesized text from each manually recorded locality, so to only
  # include country data
  for (i in 1 : length(loc)) {
    loc[i] <- str_remove_all(loc, ' ?\\(.+\\) ?')
  }
  
  true_pos = sum(pred_loc %in% loc)  # correctly predicted countries
  false_pos = sum(!(pred_loc %in% loc))  # falsely identified countries
  false_neg = sum(!(loc %in% pred_loc))  # missed countries
  
  precision = (true_pos / (true_pos + false_pos))
  recall = (true_pos / (true_pos + false_neg))
  
  # return comma separated string of precision and recall
  return(str_c(precision, recall, sep = ','))
}

# check_predicted_locality <- microsp_data %>%
#   select(species, predicted_locality, Locality, first_paper_title, abstract) %>%
#   rowwise() %>%
#   mutate(precision_recall =
#            get_predicted_locality_precision_recall(predicted_locality, Locality)) %>%
#   extract(precision_recall, c('precision', 'recall'), ',')

################################################################################

## Evaluate polar tube predictions

################################################################################

## Evaluate host predictions